### ISSUE TITLE
how to visualize each keyframe pose

### ISSUE THREAD

**Issue by rginjapan** [vkopli/gtsam_vio#2]
Thank u for your work.
For now,  I can run the rviz to see the current camera pose relative to the world frame, however ,I can not see the odometry with your rviz config. 
https://drive.google.com/file/d/1WMaj3uvE_yWq9Xk8-rDbvm3yph8Aq41n/view?usp=sharing

I run with zed mini camera(stereo+IMU).
Thanks ahead!

**Comment by vkopli** [comment]
The rviz config is set up to receive messages from the /zed/zed_node/odom topic, but your camera may be publishing the odom information to a different topic. If that's the case, you can add the topic to your rviz config and remove the one that is already there.

**Comment by leyuan-sun** [comment]
I change the transform between the odom and world in launch file, it can run on real zedmini camera now.
 Publish static transform between world and odom to visualized odom message from camera 

 node pkg="tf" type="static_transform_publisher" name="odom_broadcaster" args="0 0 0 0 0 0 odom world 100" 

https://drive.google.com/file/d/1436U_2K_aulz86ZSUDGsEiqvyCg_nSQQ/view?usp=sharing
